Task5/WebOrdersInfo/WebOrdersInfo/Models/ViewModels/Clients/ClientViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace WebOrdersInfo.Models.ViewModels.Clients
{
    public class ClientViewModel
    {
        public Guid Id { get; set; }

        [Required]
        [Display(Name = "Фамилия клиента")]
        public string Name { get; set; }
    }
}

Task5/WebOrdersInfo/WebOrdersInfo/Models/ViewModels/Clients/CreateClientViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace WebOrdersInfo.Models.ViewModels.Clients
{
    public class CreateClientViewModel
    {
        [Required]
        [Display(Name = "Фамилия клиента")]
        public string Name { get; set; }
    }
}

Task5/WebOrdersInfo/WebOrdersInfo/Controllers/ClientsController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using WebOrdersInfo.Core.DTOs;
using WebOrdersInfo.Core.Services.Interfaces;
using WebOrdersInfo.Models.ViewModels.Clients;

namespace WebOrdersInfo.Controllers
{
    [Authorize(Roles = "admin")]
    public class ClientsController : Controller
    {
        private readonly IClientService _clientService;
        private readonly IMapper _mapper;
        private readonly ILogger<ClientsController> _logger;

        public ClientsController(IClientService clientService, IMapper mapper, ILogger<ClientsController> logger)
        {
            _clientService = clientService;
            _mapper = mapper;
            _logger = logger;
        }

        public async Task<IActionResult> Index(
            string sortOrder,
            string currentFilter,
            string searchString,
            int? pageNumber)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSortParam"] = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            if (searchString != null || !pageNumber.HasValue)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            var clients = await _clientService.GetClientsPerPage(sortOrder, searchString, pageNumber.Value, Utilities.Constants.CLIENTS_PER_PAGE);

            return View(clients);
        }

        public IActionResult Create() => View();
        


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateClientViewModel model)
        {
            if (ModelState.IsValid)
            {
                var dto = _mapper.Map<ClientDto>(model);
                dto.Id = Guid.NewGuid();

                if (!await ClientNameExists(dto.Name))
                {
                    try
                    {
                        await _clientService.Add(dto);
                        return RedirectToAction(nameof(Index));
                    }
                    catch (DbUpdateException e)
                    {
                        _logger.LogError(e.Message);
                        ModelState.AddModelError("", "Unable to save changes. Try again.");
                    }
                }
                else
                {
                    ModelState.AddModelError("Name", "Клиент с такой фамилией уже существует");
                }
            }
            return View(model);
        }

        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var client = await _clientService.GetById(id.Value);

            if (client == null)
            {
                return NotFound();
            }

            var model = _mapper.Map<ClientViewModel>(client);

            return View(model);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ClientViewModel model)
        {
            if (ModelState.IsValid)
            {
                var dto = _mapper.Map<ClientDto>(model);

                if (!await ClientNameExists(dto.Name))
                {
                    try
                    {
                        await _clientService.Update(dto);
                        return RedirectToAction(nameof(Index));
                    }
                    catch (DbUpdateException e)
                    {
                        _logger.LogError(e.Message);
                        ModelState.AddModelError("", "Unable to save changes. Try again.");
                    }
                }
                else
                {
                    ModelState.AddModelError("Name", "Клиент с такой фамилией уже существует");
                }
            }
            return View(model);
        }

        public async Task<IActionResult> Delete(Guid? id, bool? saveChangesError = false)
        {
            if (id == null)
            {
                return NotFound();
            }

            var client = await _clientService.GetById(id.Value);

            if (client == null)
            {
                return NotFound();
            }

            if (saveChangesError.GetValueOrDefault())
            {
                ViewData["ErrorMessage"] = "Delete failed. Try again.";
            }

            var model = _mapper.Map<ClientViewModel>(client);

            return View(model);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var client = await _clientService.GetById(id);

            if (client == null)
            {
                return RedirectToAction(nameof(Index));
            }

            try
            {
                await _clientService.Delete(id);
                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateException ex)
            {
                _logger.LogError(ex.Message);
                return RedirectToAction(nameof(Delete), new { id = id, saveChangesError = true });
            }
        }

        private async Task<bool> ClientNameExists(string name)
        {
            return await _clientService.GetByName(name) != null;
        }
    }
}

Task5/WebOrdersInfo/WebOrdersInfo/Controllers/OrdersController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Linq;
using System.Threading.Tasks;
using WebOrdersInfo.Core.DTOs;
using WebOrdersInfo.Core.DTOs.Models.Filters;
using WebOrdersInfo.Core.DTOs.Models.Pagination;
using WebOrdersInfo.Core.Services.Interfaces;
using WebOrdersInfo.Extensions;
using WebOrdersInfo.Models.ViewModels.Orders;
using WebOrdersInfo.Pagination2;


namespace WebOrdersInfo.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private readonly IOrderService _orderService;
        private readonly IClientService _clientService;
        private readonly IManagerService _managerService;
        private readonly IProductService _productService;
        private readonly IFilterService _filterService;

        private readonly ILogger<OrdersController> _logger;

        private readonly IMapper _mapper;

        public OrdersController(IOrderService orderService,
            IClientService clientService,
            IManagerService managerService,
            IProductService productService,
            IFilterService filterService,
            IMapper mapper,
            ILogger<OrdersController> logger)
        {
            _orderService = orderService;
            _clientService = clientService;
            _managerService = managerService;
            _productService = productService;
            _filterService = filterService;
            _mapper = mapper;
            _logger = logger;
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var paginationFilter = new PaginationFilter();
            var filter = HttpContext.Session.GetData<OrdersFilter>("ordersFilters");

            if (filter is not { IsNeedClear: false })
            {
                try
                {
                    filter = await _filterService.GetFilter();
                }
                catch (Exception e)
                {
                    filter = null;
                    _logger.LogError(e.Message);
                }

                HttpContext.Session.SetData("ordersFilters", filter);
            }

            var ordersListWithPagination = await GetOrdersList(paginationFilter, filter);

            return View(ordersListWithPagination);
        }


        [HttpPost]
        public async Task<IActionResult> Index(PaginationFilter paginationFilter)
        {
            var filter = HttpContext.Session.GetData<OrdersFilter>("ordersFilters");

            if (filter is not { IsNeedClear: false })
            {
                return BadRequest();
            }

            var ordersListWithPagination = await GetOrdersList(paginationFilter, filter);

            return PartialView("_OrdersListWithPagination", ordersListWithPagination);
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Create()
        {
            var model = new CreateOrderViewModel
            {
                Clients = new SelectList(
                    (await _clientService.GetAll())
                    .OrderBy(e => e.Name),
                    "Id", "Name"),
                Managers = new SelectList(
                    (await _managerService.GetAll())
                    .OrderBy(e => e.Name),
                    "Id", "Name"),
                Products = new SelectList(
                    (await _productService.GetAll())
                    .OrderBy(e => e.Name),
                    "Id", "Name")
            };

            return View(model);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Create(CreateOrderViewModel order)
        {
            if (ModelState.IsValid && ValidateOrder(order))
            {
                var orderDto = _mapper.Map<OrderDto>(order);
                orderDto.Id = Guid.NewGuid();

                try
                {
                    await _orderService.Add(orderDto);
                }
                catch (Exception e)
                {
                    _logger.LogError("Order can\'t be added. " + e.Message);
                }

                return RedirectToAction(nameof(Index));
            }
            return View(order);
        }


        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _orderService.GetOrderById((Guid)id);

            if (order == null)
            {
                return NotFound();
            }

            var model = _mapper.Map<EditOrderViewModel>(order);

            model.Clients = new SelectList(
                (await _clientService.GetAll())
                .OrderBy(e => e.Name),
                "Id", "Name");
            model.Managers = new SelectList(
                (await _managerService.GetAll())
                .OrderBy(e => e.Name),
                "Id", "Name");
            model.Products = new SelectList(
                (await _productService.GetAll())
                .OrderBy(e => e.Name),
                "Id", "Name");

            return View(model);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit(EditOrderViewModel order)
        {
            if (ModelState.IsValid)
            {
                var orderDto = _mapper.Map<OrderDto>(order);
                try
                {
                    await _orderService.Update(orderDto);
                }
                catch (DbUpdateConcurrencyException)
                {
                    _logger.LogError("Order can\'t be updated");
                }
                return RedirectToAction(nameof(Index));
            }

            return View(order);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Delete(Guid id)
        {
            try
            {
                await _orderService.Delete(id);
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message);
            }

            return RedirectToAction(nameof(Index));
        }


        private async Task<OrdersListWithPaginationViewModel> GetOrdersList(PaginationFilter paginationFilter, OrdersFilter filter)
        {
            var query = _filterService.Query(filter);

            filter ??= new OrdersFilter
            {
                OrderBy = OrderSortEnum.Date
            };

            var (ordersDtoPerPage, allOrders) = await _orderService
                .GetOrdersPerPage(paginationFilter.PageNumber, paginationFilter.PageSize, query, filter.OrderBy);

            var i = paginationFilter.PageSize * (paginationFilter.PageNumber - 1) + 1;

            var ordersViewModel = ordersDtoPerPage.Select(o => new OrderViewModel
            {
                Id = o.Id,
                SequenceNumber = i++,
                Date = o.Date,
                ProductName = o.ProductName,
                Price = o.Price,
                ClientName = o.ClientName,
                ManagerName = o.ManagerName
            });

            var ordersListWithPagination = new OrdersListWithPaginationViewModel
            {
                OrderList = ordersViewModel,
                //Pagination = new Paging(paginationFilter.PageSize, paginationFilter.PageNumber, allOrders, url),
                Pagination = new PageInfo(paginationFilter.PageNumber, allOrders, paginationFilter.PageSize)
            };

            return ordersListWithPagination;
        }

        private bool ValidateOrder(CreateOrderViewModel model)
        {
            if (model.Date > DateTime.Now)
            {
                ModelState.AddModelError("Date", $"Дата заказа {model.Date} не должна быть позже сегодняшней даты.");
                return false;
            }

            return true;
        }
    }
}

Task5/WebOrdersInfo/WebOrdersInfo/Views/Clients/Create.cshtml
@model WebOrdersInfo.Models.ViewModels.Clients.CreateClientViewModel

@{
    ViewData["Title"] = "Добавление клиента";
}

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" asp-controller="Clients">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="input-group mb-3">
                <span class="input-group-text">
                    <label asp-for="Name"></label>
                </span>
                <input asp-for="Name" class="form-control"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="input-group mb-3">
                <input type="submit" value="Сохранить" class="btn btn-outline-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Вернуться к списку</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Task5/WebOrdersInfo/WebOrdersInfo/Views/Clients/Delete.cshtml
@model WebOrdersInfo.Models.ViewModels.Clients.ClientViewModel

@{
    ViewData["Title"] = "Удаление клиента";
}


<h3>Вы уверены что хотите удалить данного клиента?</h3>
<p class="text-danger">@ViewData["ErrorMessage"]</p>
<div>
    <h4>Клиент</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Удалить" class="btn btn-danger" /> |
        <a asp-action="Index">Вернуться к списку</a>
    </form>
</div>

Task5/WebOrdersInfo/WebOrdersInfo/Views/Clients/Edit.cshtml
@model WebOrdersInfo.Models.ViewModels.Clients.ClientViewModel

@{
    ViewData["Title"] = "Редактирование клиента";
}

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" asp-controller="Clients">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="input-group mb-3">
                <span class="input-group-text">
                    <label asp-for="Name"></label>
                </span>
                <input asp-for="Name" class="form-control"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="input-group mb-3">
                <input type="submit" value="Сохранить" class="btn btn-outline-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Вернуться к списку</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Task5/WebOrdersInfo/WebOrdersInfo/Views/Clients/Index.cshtml
@model WebOrdersInfo.Core.DTOs.Models.Pagination.PaginatedList<WebOrdersInfo.Core.DTOs.ClientDto>
@{ 
    ViewData["Title"] = "Список клиентов";
}

<div class="col-md-4">
    <div class="mb-3">
        <a asp-action="Create">Создать нового клиента</a>
    </div>
    <form asp-action="Index" method="get">
        <div class="input-group mb-3">
            <span id="searchLabel" class="input-group-text">
                Поиск по фамилии:
            </span>
            <input type="text" class="form-control" name="SearchString" value="@ViewData["CurrentFilter"]"/>
            <input type="submit" value="Поиск" class="btn btn-primary" />
            <a asp-action="Index" data-bs-toggle="tooltip" data-bs-placement="top" title="Сбросить фильтр">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-arrow-clockwise" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M8 3a5 5 0 1 0 4.546 2.914.5.5 0 0 1 .908-.417A6 6 0 1 1 8 2v1z"/>
                    <path d="M8 4.466V.534a.25.25 0 0 1 .41-.192l2.36 1.966c.12.1.12.284 0 .384L8.41 4.658A.25.25 0 0 1 8 4.466z"/>
                </svg>
            </a>
        </div>
    </form>

    <table class="table">
        <tr>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParam"]">Фамилия клиента</a>
            </th>
            <th></th>
        </tr>
        @foreach (var client in Model)
        {
            <tr>
                <td>@client.Name</td>
                <td>
                    <a class="btn btn-outline-primary" asp-action="Edit" asp-controller="Clients" asp-route-id="@client.Id">Изменить</a>
                    <a class="btn btn-sm btn-danger" asp-action="Delete" asp-route-id="@client.Id">Удалить</a>
                </td>
            </tr>
        }
    </table>
</div>

@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex - 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-primary @prevDisabled">
    Предыдущая
</a>
<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex + 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-primary @nextDisabled">
    Следующая
</a>

<a asp-action="Index" asp-controller="Orders">Вернуться к заказам</a>