Task5/WebOrdersInfo/WebOrdersInfo/Controllers/OrdersController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Linq;
using System.Threading.Tasks;
using WebOrdersInfo.Core.DTOs;
using WebOrdersInfo.Core.DTOs.Models.Filters;
using WebOrdersInfo.Core.DTOs.Models.Pagination;
using WebOrdersInfo.Core.Services.Interfaces;
using WebOrdersInfo.Extensions;
using WebOrdersInfo.Models.ViewModels.Orders;
using WebOrdersInfo.Pagination2;


namespace WebOrdersInfo.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private readonly IOrderService _orderService;
        private readonly IClientService _clientService;
        private readonly IManagerService _managerService;
        private readonly IProductService _productService;
        private readonly IFilterService _filterService;

        private readonly ILogger<OrdersController> _logger;

        private readonly IMapper _mapper;

        public OrdersController(IOrderService orderService,
            IClientService clientService,
            IManagerService managerService,
            IProductService productService,
            IFilterService filterService,
            IMapper mapper,
            ILogger<OrdersController> logger)
        {
            _orderService = orderService;
            _clientService = clientService;
            _managerService = managerService;
            _productService = productService;
            _filterService = filterService;
            _mapper = mapper;
            _logger = logger;
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var paginationFilter = new PaginationFilter();
            var filter = HttpContext.Session.GetData<OrdersFilter>("ordersFilters");

            if (filter is not { IsNeedClear: false })
            {
                try
                {
                    filter = await _filterService.GetFilter();
                }
                catch (Exception e)
                {
                    filter = null;
                    _logger.LogError(e.Message);
                }

                HttpContext.Session.SetData("ordersFilters", filter);
            }

            var ordersListWithPagination = await GetOrdersList(paginationFilter, filter);

            return View(ordersListWithPagination);
        }


        [HttpPost]
        public async Task<IActionResult> Index(PaginationFilter paginationFilter)
        {
            var filter = HttpContext.Session.GetData<OrdersFilter>("ordersFilters");

            if (filter is not { IsNeedClear: false })
            {
                return BadRequest();
            }

            var ordersListWithPagination = await GetOrdersList(paginationFilter, filter);

            return PartialView("_OrdersListWithPagination", ordersListWithPagination);
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Create()
        {
            var model = new CreateOrderViewModel
            {
                Clients = new SelectList(
                    (await _clientService.GetAll())
                    .OrderBy(e => e.Name),
                    "Id", "Name"),
                Managers = new SelectList(
                    (await _managerService.GetAll())
                    .OrderBy(e => e.Name),
                    "Id", "Name"),
                Products = new SelectList(
                    (await _productService.GetAll())
                    .OrderBy(e => e.Name),
                    "Id", "Name")
            };

            return View(model);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Create(CreateOrderViewModel order)
        {
            if (ModelState.IsValid && ValidateOrder(order))
            {
                var orderDto = _mapper.Map<OrderDto>(order);
                orderDto.Id = Guid.NewGuid();

                try
                {
                    await _orderService.Add(orderDto);
                }
                catch (Exception e)
                {
                    _logger.LogError("Order can\'t be added. " + e.Message);
                }

                return RedirectToAction(nameof(Index));
            }
            return View(order);
        }


        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _orderService.GetOrderById((Guid)id);

            if (order == null)
            {
                return NotFound();
            }

            var model = _mapper.Map<EditOrderViewModel>(order);

            model.Clients = new SelectList(
                (await _clientService.GetAll())
                .OrderBy(e => e.Name),
                "Id", "Name");
            model.Managers = new SelectList(
                (await _managerService.GetAll())
                .OrderBy(e => e.Name),
                "Id", "Name");
            model.Products = new SelectList(
                (await _productService.GetAll())
                .OrderBy(e => e.Name),
                "Id", "Name");

            return View(model);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit(EditOrderViewModel order)
        {
            if (ModelState.IsValid)
            {
                var orderDto = _mapper.Map<OrderDto>(order);
                try
                {
                    await _orderService.Update(orderDto);
                }
                catch (DbUpdateConcurrencyException)
                {
                    _logger.LogError("Order can\'t be updated");
                }
                return RedirectToAction(nameof(Index));
            }

            return View(order);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Delete(Guid id)
        {
            try
            {
                await _orderService.Delete(id);
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message);
            }

            return RedirectToAction(nameof(Index));
        }


        private async Task<OrdersListWithPaginationViewModel> GetOrdersList(PaginationFilter paginationFilter, OrdersFilter filter)
        {
            var query = _filterService.Query(filter);

            filter ??= new OrdersFilter
            {
                OrderBy = OrderSortEnum.Date
            };

            var (ordersDtoPerPage, allOrders) = await _orderService
                .GetOrdersPerPage(paginationFilter.PageNumber, paginationFilter.PageSize, query, filter.OrderBy);

            var i = paginationFilter.PageSize * (paginationFilter.PageNumber - 1) + 1;

            var ordersViewModel = ordersDtoPerPage.Select(o => new OrderViewModel
            {
                Id = o.Id,
                SequenceNumber = i++,
                Date = o.Date,
                ProductName = o.ProductName,
                Price = o.Price,
                ClientName = o.ClientName,
                ManagerName = o.ManagerName
            });

            var ordersListWithPagination = new OrdersListWithPaginationViewModel
            {
                OrderList = ordersViewModel,
                //Pagination = new Paging(paginationFilter.PageSize, paginationFilter.PageNumber, allOrders, url),
                Pagination = new PageInfo(paginationFilter.PageNumber, allOrders, paginationFilter.PageSize)
            };

            return ordersListWithPagination;
        }

        private bool ValidateOrder(CreateOrderViewModel model)
        {
            if (model.Date > DateTime.Now)
            {
                ModelState.AddModelError("Date", $"Дата заказа {model.Date} не должна быть позже сегодняшней даты.");
                return false;
            }

            return true;
        }
    }
}

Task5/WebOrdersInfo/WebOrdersInfo/Controllers/StatisticsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebOrdersInfo.Core.DTOs.Models.Statistics;
using WebOrdersInfo.Core.Services.Interfaces;

namespace WebOrdersInfo.Controllers
{
    [Authorize]
    public class StatisticsController : Controller
    {
        private readonly IManagerService _managerService;
        private readonly ILogger<StatisticsController> _logger;

        public StatisticsController(IManagerService managerService, ILogger<StatisticsController> logger)
        {
            _managerService = managerService;
            _logger = logger;
        }

        [AllowAnonymous]
        public IActionResult Index()
        {
            return View();
        }


        public async Task<JsonResult> TopManagersByOrders(bool fromTop, int take, string period, string groupBy)
        {
            var (from, to) = GetPeriod(period);

            try
            {
                IEnumerable<ManagerNameWithGroupingPropertyDto> result;
                switch (groupBy)
                {
                    case "ordersCount":
                    default:
                        result = await _managerService.GetManagersWithOrdersCount(take, fromTop, from, to);
                        break;
                    case "ordersPriceSum":
                        result = await _managerService.GetManagersWithTotalPrice(take, fromTop, from, to);
                        break;
                }
                var jsonResult = Json(result.Select(r => new { r.Name, r.GroupingProperty }));

                return new JsonResult(jsonResult);
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message);
                throw;
            }

        }

        private static (DateTime from, DateTime to) GetPeriod(string period)
        {
            DateTime from;
            DateTime to;
            DateTime dt = DateTime.Now.ToUniversalTime();
            switch (period)
            {
                case "thisMonth":
                default:
                    from = new DateTime(dt.Year, dt.Month, 1);
                    to = dt;
                    break;
                case "previousMonth":
                    from = new DateTime(dt.Year, dt.Month, 1).AddMonths(-1);
                    to = new DateTime(dt.Year, dt.Month, 1, 23, 59, 59).AddDays(-1);
                    break;
                case "thisYear":
                    from = new DateTime(dt.Year, 1, 1);
                    to = dt;
                    break;
                case "previousYear":
                    from = new DateTime(dt.Year - 1, 1, 1);
                    to = new DateTime(dt.Year - 1, 12, 31, 23, 59, 59);
                    break;
            }

            return (from, to);
        }
    }
}

Task5/WebOrdersInfo/WebOrdersInfo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebOrdersInfo</title>
    <link rel="stylesheet" href="~/lib/jquery-ui-1.13.1/jquery-ui.min.css"/>
    <link rel="stylesheet" href="~/lib/bootstrap-5.1.3/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/orders.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebOrdersInfo</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Orders" asp-action="Index">Заказы</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Statistics" asp-action="Index">Статистика</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                </ul>
            </div>
            <div id="modal-placeholder"></div>
            <div id="navbar-login"></div>
                
            @if (User.Identity.IsAuthenticated)
            {
                await Html.RenderPartialAsync("~/Views/Account/_Logout.cshtml");
            }
            else
            {
                await Html.RenderPartialAsync("~/Views/Account/_Login.cshtml");
            }
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2022 - WebOrdersInfo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap-5.1.3/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="~/js/loginModal.js"></script>

@await RenderSectionAsync("Scripts", required: false)
</body>
</html>